# import statements
import os
import joblib
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

# paths (project‑relative)
DATA_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "data", "ml_dataset.csv"))
MODEL_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "models"))
os.makedirs(MODEL_DIR, exist_ok=True)

def load_data() -> pd.DataFrame:
    """Load the synthetic ML dataset generated by dataset_generator.py"""
    return pd.read_csv(DATA_PATH)

def train_models(df: pd.DataFrame):
    """Train Logistic Regression (baseline) and Random Forest classifiers.
    Saves the trained models as joblib files in the models directory.
    """
    X = df.drop(columns=["case_id", "consistency_pattern"])
    y = df["consistency_pattern"]
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    # Logistic Regression (baseline)
    lr = LogisticRegression(max_iter=1000, class_weight="balanced")
    lr.fit(X_train, y_train)
    lr_pred = lr.predict(X_test)
    print("Logistic Regression report:\n", classification_report(y_test, lr_pred))
    print("Confusion matrix:\n", confusion_matrix(y_test, lr_pred))
    joblib.dump(lr, os.path.join(MODEL_DIR, "logistic_regression.pkl"))

    # Random Forest (better performance)
    rf = RandomForestClassifier(n_estimators=200, random_state=42, class_weight="balanced")
    rf.fit(X_train, y_train)
    rf_pred = rf.predict(X_test)
    print("Random Forest report:\n", classification_report(y_test, rf_pred))
    print("Confusion matrix:\n", confusion_matrix(y_test, rf_pred))
    joblib.dump(rf, os.path.join(MODEL_DIR, "random_forest.pkl"))

if __name__ == "__main__":
    df = load_data()
    train_models(df)
